### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by saladuit** [saladuit/BuzingaServ#39]
- [x] For each unique listen directive create a server class
- [x] When a duplicate listen directive is found it should be added to the server settings on a corresponding fd
- [x] before making server classes the listen directives should be checked by get addressinfo to validate it doesn't already exist
- [x] Server names should be parsed to decide which settings should be used
- [x] CGI fds should be added to pollfd
- [x] Update socket creation to use getaddrinfo
- [ ]

**Comment by Tentanus** [comment]
In my opinion this is all fixed
